services:
  resume-rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-rag-app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    restart: unless-stopped
